# Generated by Django 4.0.3 on 2022-03-14 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activitylist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='Date',
            new_name='date',
        ),
    ]
